{% set name = "apistar" %}
{% set version = "0.5.16" %}
{% set sha256 = "aab82b722bfa6562b3f26d736287b3dab3f4748834121f4beed157dfc2c274fb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.5
    - pip
  run:
    - aiofiles
    - jinja2
    - python >=3.5
    - requests
    - werkzeug
    - whitenoise

test:
  imports:
    - apistar

about:
  home: https://github.com/encode/apistar
  license: BSD 3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.md'
  summary: 'A smart Web API framework, designed for Python 3'

  doc_url: https://docs.apistar.com/
  dev_url: https://github.com/encode/apistar

extra:
  recipe-maintainers:
    - k-dominik
