{% set name = "apistar" %}
{% set version = "0.7.2" %}
{% set sha256 = "8da0d3f15748c8ed6e68914ba5b8f6dd5dff5afbe137950d07103575df0bce73" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - click
    - jinja2
    - python >=3.6
    - pyyaml
    - requests
    - typesystem >=0.2.0

test:
  imports:
    - apistar

about:
  home: https://github.com/encode/apistar
  license: BSD 3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.md'
  summary: 'API documentation, validation, mocking, and clients.'

  doc_url: https://docs.apistar.com/
  dev_url: https://github.com/encode/apistar

extra:
  recipe-maintainers:
    - k-dominik
