{% set name = "apistar" %}
{% set version = "0.6.0" %}
{% set sha256 = "4338b24468b49526ceac4a8f84046056081ee747f373ca8d0647bd6b2344c895" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.5
    - pip
  run:
    - aiofiles
    - click
    - jinja2
    - python >=3.5
    - pyyaml
    - requests
    - werkzeug
    - whitenoise

test:
  imports:
    - apistar

about:
  home: https://github.com/encode/apistar
  license: BSD 3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.md'
  summary: 'A smart Web API framework, designed for Python 3'

  doc_url: https://docs.apistar.com/
  dev_url: https://github.com/encode/apistar

extra:
  recipe-maintainers:
    - k-dominik
