travis:
  secure:
    BINSTAR_TOKEN: w1elPUSBdyqIZinFCFLAvpSwe7hvdtflTeZa312ZIs56bWB+J3uEqK2OxKG+qUJMZTGLKHeCkx0eBUtTW6OqA/sZBoDUBktN+UNskS5biIEiSU7IqggWbewov7YJIVWbaNtDfY4VxQ/E1o7/n8RbIE6Yt8s6zu9Sq6MzEYl/GK5pV8Jal8TmXUTuLhHRaIwWeilx/npzqXMq6T5EJKPwdzRUprThPVmE4gMRW3FfcD+UbiR0isFJySIq1e8nIXaYDOuTfXertgYZNGRLoPyxH6XwgBMkGdfNKHtwS6jkIX7bXlttgLofVE1NSeXkY/hJ4ZpYAMfzHQwldVrQLFHkwvyWlF35MnM5GULhgYOj3EzVlvsjtsKcA/KowdUc/mAervUrpToUpeh9E8K+J6dQAtn5AXTqIW9QjnZK0QJavAN8v6iYq0vuFW8npGN+M7kVbkFCBh65ZzuGgtEgCQsVG5TuO2txYsX2p7hIiPOnA8ba7NlHwtF91ZKzZ4NHiYfBAwl1Ss7HUlCQY3DKslOHQ1DBtlYytKpDWWQkdKQOS3AzrFJ2MQOA2s7EBU9fxxr6y0w+pXzX6dluuO9dv2dbasqInEnocei+VBYFsCezXDSr1jdVq8a9Yi5cLq9IL3Xbmus0tQWmXyXNKYsrkV6AsCcdNF4RYe0+qLThgrgrms4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
