travis:
  secure:
    BINSTAR_TOKEN: vl5zdMHnoXKhv3cF8KuTZ1KEdXXMyMx/O5UMEqo9UQVZPEGeas0qZfvuQK8spijbnBxFRSOEln9csJ/KcDanZBcYxwyqWrbZL6qdnGJgFyWpK8aM9tOtKK9mBMMKn92AVFbdLTBn/ak3R9mB6t1ChyVmxIzYHDQH33Y3K8lW5ygtjgF2aBzde4dxPyszxsnj1ySzKER+Gb/+Pju20RaVb1WVy6ZeP3HkZVrPziZmWwtnoOS7ifJvsfhYyWHmAgCwNIj+bGXHge2a7nCpJyveemSIAInJ9VL8VLRlv9Oqy3DeGlRQ6O5MvcZCwUKrs543Mx/Zn99JEwyUh2TaSVtxDsQPWIl3VD4WQXY/gIlzAYgTUIa7RnN3hgXxWpX61dCySvbiMSlmb+L2LrrwfGpjBUg4dUeJ53am9AxcBohKqx4ExPNyzf/eYk1I7EKQsZHaE+Bz3CwO/VF0EqRidvju79zQ9uCp/m4k+iwpm2Av+Y/TQlMTty6NM4pnj2DMZGgK1noimTnKlNWZVM6hyzgAvcwzyyPBLASDxLzS+irqK3BkmzwsV5jznknKNwb6nXENN34jcupmzGfjjdx8DI223eQxSKO93wSDAEa8zOka1QHDmS6UmZZXX9iirlVYYTr6ck0NpIb+lV+gVQLybComy9N6YDoTiCKcVjgDMWzbOn8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
